baseurl = "https://antux-91.github.io/adg.github.io"
title = "Winning"
theme = "hugo-theme-winning"

disableKinds = ["RSS"]
defaultContentLanguage = "en"
enableRobotsTXT = true
languageCode = "en-GB"
[taxonomies]

[author]
    name = "Antonio De Gaetano"
    email = "antoniodegaetano@criptmail.com"
