baseurl = "https://"
title = "Winning"
theme = "hugo-theme-winning"

disableKinds = ["RSS"]
defaultContentLanguage = "en"
enableRobotsTXT = true
languageCode = "en-us"
[taxonomies]

[author]
    name = "your-name"
    email = "your-email"
